# Get a comment by id
GET http://localhost:3000/comments/6959134d008c7f8f267eca0f
Accept: application/json


###
# Get comments by post
GET http://localhost:3000/comments?postId=69590fb0b0961d8c8a7931d
Accept: application/json
Authorization: Bearer <TOKEN>


###
# Add a new comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "content": "This is a test comment",
  "postId": "69590fb0b0961d8c8a7931de",
  "authorId": "69590f00d8cfe5f37f38ca02"
}


###
# Update a comment
PUT http://localhost:3000/comments/695915edbf28140b374f0d37
Content-Type: application/json

{
  "content": "This is the new content of the comment",
  "postId": "69590fb0b0961d8c8a7931de",
  "authorId": "69590f00d8cfe5f37f38ca02"
}


###
# Delete a comment
DELETE http://localhost:3000/comments/695915edbf28140b374f0d33