# Get all posts
GET http://localhost:3000/posts
Content-Type: application/json
Cookie: accessToken=<token>


###
# Get a post by id
GET http://localhost:3000/posts/693d6f4cf91d8fc96c6a3cf9
Content-Type: application/json
Cookie: accessToken=<token>


###
# Get posts by author
GET http://localhost:3000/posts?authorId=69cebc9700d29dcd169aef6d
Content-Type: application/json
Cookie: accessToken=<token>


###
# Add a new post
POST http://localhost:3000/posts
Content-Type: application/json
Cookie: accessToken=<token>

{
  "title": "Hello World",
  "content": "This is a test post",
  "type": "Other"
}


###
# Update a post
PUT http://localhost:3000/posts/69cec0b462b66ed449aae5d3
Content-Type: application/json
Cookie: accessToken=<token>

{
  "content": "This is an updated test post",
  "type": "Donation"
}


###
# Delete a post
DELETE http://localhost:3000/posts/69cec0b462b66ed449aae5d3
Content-Type: application/json
Cookie: accessToken=<token>


###
# Like a post
POST http://localhost:3000/posts/like/69cebd3100d29dcd169aef92
Content-Type: application/json
Cookie: accessToken=<token>


###
# Unlike a post
POST http://localhost:3000/posts/unlike/69cebd3100d29dcd169aef92
Content-Type: application/json
Cookie: accessToken=<token>


###
# Get posts in batch (paginated)
GET http://localhost:3000/posts/batch?page=0&limit=10
Content-Type: application/json
Cookie: accessToken=<token>